version: "3"
services:
    backuper:
        image: elyspio/backup-maker
        ports:
            - "4009:4000"
        volumes:
            - ./config/front/conf.js:/front/conf.js
            - ./config/back/config.json:/back/config.json
        environment:
            CONFIG_PATH: /back/config.json

volumes:
    backup-maker:
        driver: local
