version: "3"
services:
    backup-maker:
        container_name: backup-maker
        image: elyspio/backup-maker
        restart: always
        volumes:
            - "./config/front/conf.js:/back/wwwroot/conf.js"
            - "./config/back/appsettings.docker.json:/back/appsettings.docker.json"
            - "/backup/mongo/:/backup/"
        networks:
            - external
            - internal
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=external"
            - "traefik.http.middlewares.backup-maker-prefix.stripprefix.prefixes=/backup"
            - "traefik.http.routers.backup-maker.middlewares=backup-maker-prefix@docker"
            - "traefik.http.routers.backup-maker.rule=PathPrefix(`/backup`)"
            - "traefik.http.services.backup-maker.loadbalancer.server.port=4000"
            - "traefik.http.routers.backup-maker.entrypoints=external"

networks:
    external:
        external: true
    internal:
        external: true
    
